<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-25T13:34:48Z" name="Suite" finished-at="2020-09-25T13:35:28Z" duration-ms="40185">
    <groups>
    </groups>
    <test started-at="2020-09-25T13:34:48Z" name="Test" finished-at="2020-09-25T13:35:28Z" duration-ms="40185">
      <class name="com.versapay.qa.testcases.Test">
        <test-method is-config="true" signature="logerSetUp()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:34:48Z" name="logerSetUp" finished-at="2020-09-25T13:34:48Z" duration-ms="38" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logerSetUp -->
        <test-method is-config="true" signature="StartUp()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:34:48Z" name="StartUp" finished-at="2020-09-25T13:34:58Z" duration-ms="9831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartUp -->
        <test-method signature="MethodOne()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:34:58Z" name="MethodOne" finished-at="2020-09-25T13:34:58Z" duration-ms="159" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [VersaPay | Automated Accounts Receivable Software] but found [VersaPa | Automated Accounts Receivable Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [VersaPay | Automated Accounts Receivable Software] but found [VersaPa | Automated Accounts Receivable Software]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.versapay.qa.testcases.Test.MethodOne(Test.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MethodOne -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:34:58Z" name="tearDown" finished-at="2020-09-25T13:34:58Z" duration-ms="729" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="StartUp()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:34:59Z" name="StartUp" finished-at="2020-09-25T13:35:07Z" duration-ms="8558" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartUp -->
        <test-method signature="MethodOne()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:07Z" name="MethodOne" finished-at="2020-09-25T13:35:07Z" duration-ms="25" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [VersaPay | Automated Accounts Receivable Software] but found [VersaPa | Automated Accounts Receivable Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [VersaPay | Automated Accounts Receivable Software] but found [VersaPa | Automated Accounts Receivable Software]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.versapay.qa.testcases.Test.MethodOne(Test.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MethodOne -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:07Z" name="tearDown" finished-at="2020-09-25T13:35:08Z" duration-ms="748" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="StartUp()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:08Z" name="StartUp" finished-at="2020-09-25T13:35:16Z" duration-ms="8552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartUp -->
        <test-method signature="MethodOne()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:16Z" name="MethodOne" finished-at="2020-09-25T13:35:16Z" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [VersaPay | Automated Accounts Receivable Software] but found [VersaPa | Automated Accounts Receivable Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [VersaPay | Automated Accounts Receivable Software] but found [VersaPa | Automated Accounts Receivable Software]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.versapay.qa.testcases.Test.MethodOne(Test.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MethodOne -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:18Z" name="tearDown" finished-at="2020-09-25T13:35:19Z" duration-ms="728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="StartUp()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:19Z" name="StartUp" finished-at="2020-09-25T13:35:27Z" duration-ms="8408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartUp -->
        <test-method signature="MethodTwo()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:27Z" name="MethodTwo" finished-at="2020-09-25T13:35:27Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MethodTwo -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.versapay.qa.testcases.Test@60704c]" started-at="2020-09-25T13:35:27Z" name="tearDown" finished-at="2020-09-25T13:35:28Z" duration-ms="699" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.versapay.qa.testcases.Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
